name: Deploy GH Pages

on:
  push:
    branches: 
      [main]
    paths:
    - '.github/workflows/deploy.yml'
  pull_request:
    branches: 
      [main]

jobs:
  docs-build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Deploy
      run: npm i && npm run deploy
